name: json_schema
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
# custom <json_schema dependencies>

  path:
  logging:
  logging_handlers:

dev_dependencies:

  unittest:
  hop: "0.24.2"

# end <json_schema dependencies>

