name: json_schema
version: 3.0.1
description: Provide support for validating instances against json schema
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: '>=0.13.7 <3.0.0'
  collection: ^1.14.6
  http: ^0.13.3
  logging: '>=0.9.3 <2.0.0'
  path: ^1.3.0
  rfc_6901: ^0.1.0
  uri: '>=0.11.1 <2.0.0'

dev_dependencies:
  dependency_validator: ^3.1.2
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  test: ^1.9.1
  workiva_analysis_options: ^1.2.2
