name: json_schema
version: 1.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
dependencies:

# custom <json_schema dependencies>

  path: "^1.3.0"

# end <json_schema dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <json_schema dev dependencies>

  test: "^0.12.0"
  ebisu: "^0.1.0"
  yaml: "^2.1.0"

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <json_schema dev dependencies>

dependency_overrides:
# custom <json_schema dependency overrides>
# end <json_schema dependency overrides>

transformers:

# custom <json_schema transformers>
# end <json_schema transformers>

