name: json_schema
version: 0.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
dependencies:
  path: ">=0.7.1"

  logging: ">=0.7.1"

# custom <json_schema dependencies>

# end <json_schema dependencies>

dev_dependencies:
  unittest: ">=0.7.1"

  hop: ">=0.24.4"

# custom <json_schema dev dependencies>

# end <json_schema dev dependencies>


