name: json_schema
version: 3.0.1
description: Provide support for validating instances against json schema
homepage: https://github.com/workiva/json_schema

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: '>=0.13.7 <3.0.0'
  collection: ^1.14.6
  json_pointer: ^0.1.0
  logging: '>=0.9.3 <2.0.0'
  path: ^1.3.0
  uri: '>=0.11.1 <2.0.0'
  w_transport: ^4.0.0

dev_dependencies:
  dart_dev: ^3.6.1
  dependency_validator: ^1.4.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test: ^1.9.1
  workiva_analysis_options: ^1.2.2
