name: json_schema
version: 1.0.4
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:

# custom <json_schema dependencies>

  path: "^1.3.0"
  logging: ">=0.9.3<0.12.0"
  args: ">=0.11.0 <0.14.0"

# end <json_schema dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"

# custom <json_schema dev dependencies>

  ebisu: "^0.7.3"
  test: "^0.12.13"
  yaml: "^2.1.0"
  coverage: ">=0.7.6"

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <json_schema dev dependencies>

dependency_overrides:
# custom <json_schema dependency overrides>

#  ebisu:
#    path: ../ebisu

# end <json_schema dependency overrides>

transformers:

# custom <json_schema transformers>
# end <json_schema transformers>

