name: json_schema
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
dependencies:
# custom <json_schema dependencies>

  path: ">=0.6.21+3"
  logging: ">=0.5.0+1"
  logging_handlers: ">=0.5.0+2"

dev_dependencies:

  unittest: ">=0.6.21+3"
  hop: "0.24.2"

# end <json_schema dependencies>

