name: json_schema
version: 1.0.7

authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
  
homepage: https://github.com/workiva/json_schema
description: >
  Provide support for validating instances against json schema
environment:
  sdk: ">=1.8.2 <2.0.0"

dependencies:
  path: "^1.3.0"
  logging: ">=0.9.3<0.12.0"
  args: ">=0.11.0 <2.0.0"

dev_dependencies:
  test: "^0.12.13"
  yaml: "^2.1.0"
  coverage: ">=0.7.6"
