name: json_schema
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/json_schema
description: >
  Provide support for validating instances against json schema
dependencies:
  path: "any"

  logging: ">=0.6.21+3 <0.6.22"

  logging_handlers: ">=0.5.0+3 <0.5.1"

# custom <json_schema dependencies>

  path: ">=0.6.21+3"

# end <json_schema dependencies>

dev_dependencies:
  hop: "0.24.2"

# custom <json_schema dev dependencies>

  unittest: ">=0.6.21+3"

# end <json_schema dev dependencies>


