name: Publish

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create-sbom-release-asset:
    name: Create SBOM Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
  publish:
    name: Publish to pub.dev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
