name: Publish

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create-sbom-release-asset:
    name: Create SBOM Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
  # TODO https://github.com/Workiva/json_schema/issues/184
  # Based on https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run --skip-validation
      - name: Publish
        run: dart pub publish -f
